### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by andrei-p79** [optimaize/nameapi-client-java#4]
Hi, guys!
Why am I receiving this error?
Bad HTTP status code: 403 Client Error: AccessDenied for url: http://rc50-api.nameapi.org/rest/v5.0/parser/personnameparser?apiKey=

**My account is: andrei.p@travod.com**

I have a paid package of 20k (one-time) and here are my stats
![image](https://user-images.githubusercontent.com/71407055/174599597-b6b0bcd9-100c-4e36-8199-84f585732c5e.png)

**Comment by nicoletorres** [comment]
Hi Andrei,

The correct URL is now:
https://api.nameapi.org/rest/v5.3/parser/personnameparser?apiKey=

The documentation and _readme_ has been updated accordingly.

**Comment by andrei-p79** [comment]
Thanks, @nicoletorres
